#!/usr/bin/env node
/**
 * Copy static assets into public/ for Astro build.
 * All HTML pages are generated by Astro from pages-manifest.json.
 */
import { cpSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PUBLIC = join(ROOT, 'public');

const COPY_DIRS = [
  'css',
  'js',
  'assets',
  'CMS',
  'components',
  'solutions/components',
  'blog-posts/index.json',
  'blog-posts/img',
];

const COPY_FILES = [
  'rss.xml',
  'rss-it.xml',
  'robots.txt',
  'CNAME',
  'ai.txt',
  'llms.txt',
  'llms-full.txt',
];

function copyRecursive(src, dest) {
  cpSync(src, dest, { recursive: true, force: true });
}

function main() {
  if (existsSync(PUBLIC)) {
    rmSync(PUBLIC, { recursive: true, force: true });
  }
  mkdirSync(PUBLIC, { recursive: true });

  for (const item of COPY_DIRS) {
    const src = join(ROOT, item);
    if (!existsSync(src)) continue;
    const dest = join(PUBLIC, item);
    if (item.includes('.json')) {
      mkdirSync(dirname(dest), { recursive: true });
      cpSync(src, dest);
    } else {
      copyRecursive(src, dest);
    }
    console.log(`Copied ${item}`);
  }

  for (const file of COPY_FILES) {
    const src = join(ROOT, file);
    if (!existsSync(src)) continue;
    cpSync(src, join(PUBLIC, file));
    console.log(`Copied ${file}`);
  }

  console.log('public/ sync complete (assets only).');
}

main();
